SNOWPACK <- function(SNDEN, WE, SLIQ, SNTMP, dt, SPACK) {
  # parameters
  C1 <- SPACK$C1
  C2 <- SPACK$C2
  C3 <- SPACK$C3
  C4 <- SPACK$C4
  THRESD <- SPACK$THRESD
  C5 <- SPACK$C5
  CX <- SPACK$CX
  mDEC_RHO_COMPACTION <- SPACK$mDEC_RHO_COMPACTION
  mDEC_RHO_DM_METAMORPH <- SPACK$mDEC_RHO_DM_METAMORPH
  
  # CONVERT WATER EQUIVALENT TO CENTIMETERS
  WECM <- WE * 0.1
  
  #### CALCULATE CHANGE IN DENSITY AS A RESULT OF COMPACTION
  # C1 IS THE FRACTIONAL INCREASE IN DENSITY (1/(CM*HR))
  # C2 IS A CONSTANT (CM3/G) Kojima estimated as 21 cms/g
  DCC <- 1
  if (mDEC_RHO_COMPACTION == 1) {
    if (WECM > (1E-2)) {
      B <- dt * C1 * exp(0.08 * SNTMP - C2 * SNDEN)
      DCC <- (exp(B * WECM) - 1) / (B * WECM)
    }
  }
  
  ### CALCULATE THE DENSITY CHANGE AS A RESULT OF DESTRUCTIVE
  # METAMORPHISM AND COMPONENT OF MELT METAPHORISM DUE TO
  # THE PRESENCE OF LIQUID WATER
  # C3 IS THE FRACTIONAL SETTLING RATE AT 0 DEGREE FOR DENSITIES
  # LESS THAN THRESHOLD DENSITY, THRESD
  # C4 IS A CONSTANT
  # C5 IS AN EMPIRICAL ADJUSTMENT FACTOR THAT ACCOUNTS FOR
  # THE PRESENCE OF LIQUID WATER
  DCD <- 1
  if (mDEC_RHO_DM_METAMORPH == 1) {
    A1 <- C3
    if (SLIQ > 0) {
      A1 <- A1 * C5
    }
    A2 <- C4 * SNTMP
    
    if (SNDEN > THRESD) {
      A2 <- A2 - CX * (SNDEN - THRESD)
    }
    
    A <- A1 * dt * exp(A2)
    DCD <- exp(A)
  }
  
  SNDEN <- SNDEN * DCC * DCD
  
  SNDPT <- WECM / SNDEN
  
  return(list(SNDEN = SNDEN, SNDPT = SNDPT))
}


