
# subfunction: SNOWPACK
# CALCULATES SNOW COMPACTION AND DESTRUCTIVE
# METAMORPHISM - ALSO COMPONENT OF MELT METAMORPHISM DUE
# TO THE PRESENCE OF LIQUID WATER IS ACCOUNTED FOR

SNOWPACK <- function(SNDEN, WE, SLIQ, SNTMP, dt, SPACK) {
  
  # parameters
  C1 <- SPACK$C1
  C2 <- SPACK$C2
  C3 <- SPACK$C3
  C4 <- SPACK$C4
  THRESD <- SPACK$THRESD
  C5 <- SPACK$C5
  CX <- SPACK$CX
  
  # CONVERT WATER EQUIVALENT TO CENTIMETERS
  WECM <- WE * 0.1
  
  #### CALCULATE CHANGE IN DENSITY AS A RESULT OF COMPACTION
  # C1 IS THE FRACTIONAL INCREASE IN DENSITY (1/(CM*HR))
  # C2 IS A CONSTANT (CM3/G) Kojima estimated as 21 cms/g
  
  DCC <- rep(1, length(SNDEN))
  
  B <- dt * C1 * exp(0.08 * SNTMP - C2 * SNDEN)
  w1 <- which(WECM > 1E-2)
  DCC[w1] <- (exp(B[w1] * WECM[w1]) - 1) / (B[w1] * WECM[w1])
  
  
  #### CALCULATE THE DENSITY CHANGE AS A RESULT OF DESTRUCTIVE
  # METAMORPHISM AND COMPONENT OF MELT METAPHORISM DUE TO
  # THE PRESENCE OF LIQUID WATER
  # C3 IS THE FRACTIONAL SETTLING RATE AT 0 DEGREE FOR DENSITIES
  # LESS THAN THRESHOLD DENSITY, THRESD
  # C4 IS A CONSTANT
  # C5 IS AN EMPIRICAL ADJUSTMENT FACTOR THAT ACCOUNTS FOR
  # THE PRESENCE OF LIQUID WATER
  
  A1 <- C3
  f1 <- which(SLIQ > 0)
  A1[f1] <- A1[f1] * C5[f1]
  A2 <- C4 * SNTMP
  
  f1 <- which(SNDEN > THRESD)
  A2[f1] <- A2[f1] - CX[f1] * (SNDEN[f1] - THRESD[f1])
  
  A <- A1 * dt * exp(A2)
  DCD <- exp(A)
  
  # NEW SNOW DENSITY OF EXISTING SNOW AS A RESULT OF COMPACTION
  # AND DESTRUCTIVE METAMORPHISM
  SNDEN <- SNDEN * DCC * DCD
  
  # NEW DEPTH OF EXISTING SNOW AFTER DENSITY CHANGE
  SNDPT <- WECM / SNDEN
  
  return(list(SNDEN = SNDEN, SNDPT = SNDPT))
  
}
