SNOWT <- function(DPTNEW, SNDEN, SNDPT, WE, SLIQ, SNTMP, DTA, dt) {
  # Parameters
  CICE <- 2.1E06
  CH2O <- 4.2E06
  CAIR <- 1E03
  
  # HEAT WAVE LENGTH, IN SECONDS
  WAVEL <- 2.0 * 3600 * dt
  
  # CONVERT DEPTHS TO METERS
  SNDPTM <- 0.01 * SNDPT
  DPTNWM <- 0.01 * DPTNEW
  
  # GET TOTAL WATER EQUIVALENT AND DENSITY (SOLID PLUS LIQUID WATER)
  WETOT <- WE + SLIQ
  DENTOT <- 0.1 * WETOT / SNDPT
  
  # COMPUTE THERMAL CONDUCTIVITY
  TC <- 0.0442 * exp(5.181 * DENTOT)
  
  # COMPUTE FRACTION LIQUID
  FL <- SLIQ / WETOT
  
  # COMPUTE EFFECTIVE SPECIFIC VOLUMETRIC HEAT CAPACITY
  C <- CICE * SNDEN + CAIR * (1 - SNDEN - FL) + CH2O * FL
  
  # COMPUTE NEW SNOW COVER TEMPERATURE
  ALP <- sqrt(pi * C / (WAVEL * TC))
  
  if (DPTNEW > 0) {
    SNTMP <- SNTMP + DTA * ((exp(-ALP * DPTNWM) - exp(-ALP * SNDPTM)) / (ALP * (SNDPTM - DPTNWM)))
  } else {
    SNTMP <- SNTMP + DTA * ((1 - exp(-ALP * SNDPTM)) / (ALP * SNDPTM))
  }
  
  SNTMP <- min(SNTMP, 0, na.rm = TRUE)
  
  return(SNTMP)
}


